version: '3.8'

services:
  web:
    build: .
    container_name: portfolio_web
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_net
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  backend_net:

volumes:
  db_data:

